# Generated by Django 4.2.14 on 2024-08-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='clicks',
            new_name='num_clicks',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
