# Generated by Django 4.2.14 on 2024-08-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_clicks_habit_num_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='num_clicks',
        ),
        migrations.AddField(
            model_name='habit',
            name='num_click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
