# Generated by Django 4.2.14 on 2024-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_habit_num_clicks_habit_num_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
