# Generated by Django 4.2.14 on 2024-08-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_film_actor_alter_film_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chính kịch', 'Chính kịch'), ('Âm nhạc', 'Âm nhạc'), ('Nhạc kịch', 'Nhạc kịch'), ('Giả tưởng', 'Giả tưởng'), ('Hành động', 'Hành động'), ('Phiêu lưu', 'Phiêu lưu'), ('Hài kịch', 'Hài kịch'), ('Bí ẩn', 'Bí ẩn'), ('Khoa học viễn tưởng', 'Khoa học viễn tưởng'), ('Phim ngắn', 'Phim ngắn'), ('Kinh dị tâm lý', 'Kinh dị tâm lý'), ('Kinh dị', 'Kinh dị'), ('Tiểu sử', 'Tiểu sử'), ('Thể thao', 'Thể thao'), ('Lãng mạn', 'Lãng mạn'), ('Gia đình', 'Gia đình'), ('Lịch sử', 'Lịch sử'), ('Hoạt hình', 'Hoạt hình'), ('Tài liệu', 'Tài liệu'), ('Hình sự', 'Hình sự'), ('Chiến tranh', 'Chiến tranh'), ('Miền Tây hoang dã', 'Miền Tây hoang dã'), ('Trực tiếp', 'Trực tiếp'), ('Trò chơi truyền hình', 'Trò chơi truyền hình'), ('Thoại mục', 'Thoại mục'), ('Tin tức', 'Tin tức'), ('Phim người lớn', 'Phim người lớn')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='app.genre'),
        ),
    ]
