# Generated by Django 4.2.14 on 2024-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_genre_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.IntegerField(default=2024),
        ),
    ]
