# Generated by Django 4.2.14 on 2024-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_film_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
