# Generated by Django 4.2.14 on 2024-08-18 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bill_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 14, 50, 15, 906186)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('P', 'Complete'), ('E', 'Error'), ('C', 'Cancelled'), ('N', 'Not Complete')], default='N', max_length=2),
        ),
    ]
