# Generated by Django 4.2.14 on 2024-08-18 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_bill_payment_date_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 15, 25, 23, 465668)),
        ),
    ]
