# Generated by Django 4.2.14 on 2024-08-18 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_bill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 15, 55, 39, 301157)),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
