# Generated by Django 4.2.14 on 2024-08-18 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_bill_payment_date_remove_film_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 16, 41, 11, 724353)),
        ),
    ]
