# Generated by Django 4.2.14 on 2024-08-19 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_bill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 8, 16, 40, 855454)),
        ),
    ]
