# Generated by Django 4.2.14 on 2024-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_bill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('P', 'Đã thanh toán'), ('E', 'Lỗi'), ('C', 'Đã huỷ'), ('N', 'Chưa thanh toán')], default='N', max_length=2),
        ),
    ]
