# Generated by Django 4.2.14 on 2024-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='film',
            name='author',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(to='ViewProduct.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='author',
            field=models.ManyToManyField(to='ViewProduct.author'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='ViewProduct.genre'),
        ),
    ]
