# Generated by Django 4.2.14 on 2024-08-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewProduct', '0003_alter_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
