# Generated by Django 4.2.14 on 2024-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
